# Generated by Django 3.1 on 2023-11-03 13:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sales.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'STARTED'), (2, 'SUCCESS'), (3, 'FAILURE')], default=0)),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file', models.FileField(upload_to=sales.models.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv'])])),
            ],
        ),
        migrations.CreateModel(
            name='SaleError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='sales.sale')),
            ],
        ),
    ]
